version: "3.7"

services:
  consumption:
    build: .
    command: consumption-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
  postgres:
    build: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
